blank_issues_enabled: true
contact_links:
  - name: "Contributor Guide"
    url: "https://github.com/fahimahammed/DevUI#contributing"
    about: "Read contribution guidelines (if available)."
template_selector:
  - "🐛 Bug report"
  - "📚 Documentation update"
  - "✨ Feature request"
