name: Deploy to Vercel (v2)
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
on:
  push:
    branches:
      - main

jobs:
  vercel-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest pnpm
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
      - name: Build Project Artifacts
        run: vercel build --token=$VERCEL_TOKEN
      - name: Deploy Preview to Vercel
        id: vercel
        run: |
          DEPLOY_URL=$(vercel --prebuilt --token=$VERCEL_TOKEN --confirm --scope ${{ env.VERCEL_ORG_ID }} --prod=false)
          echo "preview_url=$DEPLOY_URL" >> $GITHUB_OUTPUT

      - name: Show Preview URL
        run: echo "Preview URL- ${{ steps.vercel.outputs.preview_url }}"