name: Vercel Preview Deploy

on:
  pull_request:
    branches:
      - '**' # Trigger on all PRs

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  vercel-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Info
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel pull --yes --environment=preview

      - name: Build Project
        env:
          NEXT_PUBLIC_VERCEL_ENV: preview
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel build

      - name: Deploy Preview to Vercel
        id: vercel_deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          url=$(vercel deploy --prebuilt --confirm)
          echo "preview_url=$url" >> $GITHUB_OUTPUT

      - name: Comment Preview URL on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: vercel-preview
          message: |
            🚀 Vercel Preview Deployment Ready!
            🔗 [View Preview Deployment](${{ steps.vercel_deploy.outputs.preview_url }})
